version: 2
jobs:
  build:
    working_directory: ~/circleci-demo-python-django
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run:
          command: |
            pip install django
            pip install coverage==3.6
            pip install django-crispy-forms
            pip install Pillow
      - run:
          command: |
            cd django_blog
            python manage.py makemigrations
            python manage.py migrate
            coverage run --omit=manage.py manage.py test blog.tests news.tests socialmedia.tests videos.tests
            coverage report
destination: tr1
